import os

file_path = "c:/DARKO/KalkulacijaPetric/TISKOVNA POLA/tiskovna-pola-kalkulator.html"

with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

replacements = {
    "Prepre\ufffdi": "Prepreči",
    "STATI\ufffdNA": "STATIČNA",
    "Prika\ufffdi": "Prikaži",
    "POVE\ufffdI": "POVEŽI",
    "monta\ufffdo": "montažo",
    "Su\ufffdnik": "Sušnik",
    "Sa\ufffdo": "Sašo",
    "Slemen\ufffdek": "Slemenšek",
    "Naro\ufffdena": "Naročena",
    "Le\ufffde": "Leže",
    "Pokon\ufffdno": "Pokončno",
    "Izra\ufffdunaj": "Izračunaj",
    "povr\ufffdine": "površine",
    "Vpi\ufffdi": "Vpiši",
    "KO\ufffdARICA": "KOŠARICA",
    "bolj\ufffdo": "boljšo",
    "Po\ufffdisti": "Počisti",
    "Stro\ufffdkov": "Stroškov",
    "Obra\ufffdanje": "Obračanje",
    "izra\ufffdunano": "izračunano",
    "obra\ufffdanje": "obračanje",
    "pav\ufffdal": "pavšal",
    "izra\ufffdunana": "izračunana",
    "Na\ufffdin": "Način",
    "obra\ufffduna": "obračuna",
    "Osve\ufffdi": "Osveži",
    "stro\ufffdke": "stroške",
    "no\ufffda": "noža",
    "Ro\ufffdno": "Ročno",
    "Ro\ufffdni": "Ročni",
    "Po\ufffdta": "Pošta",
    "stro\ufffdek": "strošek",
    "Mar\ufffda": "Marža",
    "Stro\ufffdek": "Strošek",
    "ozna\ufffdevanje": "označevanje",
    "razli\ufffdna": "različna",
    "Osve\ufffduj": "Osvežuj",
    "Osve\ufffdevanje": "Osveževanje",
    "ko\ufffdarice": "košarice",
    "Prepri\ufffdaj": "Prepričaj",
    "izra\ufffdun": "izračun",
    "izra\ufffdunu": "izračunu",
    "ko\ufffdarico": "košico", # košarico
    "Izbri\ufffdem": "Izbrišem",
    "Ko\ufffdarica": "Košarica",
    "obra\ufffdanja": "obračanja",
    "me\ufffdana": "mešana",
    "ro\ufffdno": "ročno",
    "nesimetri\ufffdne": "nesimetrične",
    "po\ufffdistimo": "počistimo",
    "ro\ufffdni": "ročni",
    "zmanj\ufffdajte": "zmanjšajte",
    "vklju\ufffdno": "vključno",
    "na\ufffdinu": "načinu",
    "Te\ufffda": "Teža",
    "Pav\ufffdalna": "Pavšalna",
    "Izra\ufffdunamo": "Izračunamo",
    "na\ufffdine": "načine",
    "izra\ufffduna": "izračuna",
    "Obra\ufffdalnik": "Obračalnik",
    "upo\ufffdtevamo": "upoštevamo",
    "pri\ufffdtejemo": "prištejemo",
    "mar\ufffda": "marža",
    "naro\ufffdeno": "naročeno",
    "razre\ufffde": "razreže",
    "po\ufffdta": "pošta",
    "grafi\ufffdno": "grafično",
    "najbolj\ufffdo": "najboljšo",
    "la\ufffdji": "lažji",
    "zna\ufffdka": "značka",
    "Nari\ufffdemo": "Narišemo",
    "RO\ufffdNI": "ROČNI",
    "uravnote\ufffdeno": "uravnoteženo",
    "mre\ufffdo": "mrežo",
    "vi\ufffdino": "višino",
    "Izra\ufffdun": "Izračun",
    "simetri\ufffdnih": "simetričnih",
    "simetri\ufffdno": "simetrično",
    "vi\ufffdje": "višje",
    "Me\ufffdana": "Mešana",
    "nari\ufffdi": "nariši",
    "ZA\ufffdETKA": "ZAČETKA",
    "izklju\ufffdno": "izključno",
    "uspe\ufffdno": "uspešno",
    "nalo\ufffdena": "naložena",
    "uvo\ufffden": "uvožen",
    "Bri\ufffdi": "Briši",
    "Pomo\ufffdna": "Pomožna",
    "nalo\ufffden": "naložen",
    "prepri\ufffdani": "prepričani",
    "ko\ufffdarica": "košarica",
    "MONTA\ufffdA": "MONTAŽA",
    "MONTA\ufffdNI": "MONTAŽNI",
    "Manjkajo\ufffdi": "Manjkajoči",
    "Tovarni\ufffdka": "Tovarniška",
    "f\ufffdr": "für",
    "k\ufffdnnen": "können",
    "Va\ufffde": "Vaše",
    "povpra\ufffdevanje": "povpraševanje",
    "Naro\ufffdnik": "Naročnik",
    "m\ufffdgliche": "mögliche",
    "w\ufffdnschen": "wünschen",
    "vra\ufffdunan": "vračunan",
    "pla\ufffdila": "plačila",
    "tehni\ufffdnih": "tehničnih",
    "Pod\ufffdrtano": "Podčrtano",
    "Prera\ufffdunaj": "Preračunaj",
    "kasnej\ufffdo": "kasnejšo",
    "monta\ufffda": "montaža",
    "Koli\ufffdina": "Količina",
    "to\ufffdno": "točno",
    "koli\ufffdino": "količino",
    "Na\ufffda": "Naša",
    "pokli\ufffdi": "pokliči",
    "omogo\ufffdite": "omogočite",
    "monta\ufffdnega": "montažnega",
    "nPri\ufffdakovana": "nPričakovana",
    "uvo\ufffdena": "uvožena",
    "prej\ufffdnjo": "prejšnjo",
    "izri\ufffdi": "izriši",
    "logi\ufffdno": "logično",
    "za\ufffdnemo": "začnemo",
    "Po\ufffdakaj": "Počakaj",
    "prika\ufffde": "prikaže",
    "po\ufffdistim": "počistim",
    "na\ufffdtimali": "naštimali",
    "Monta\ufffdni": "Montažni",
    "monta\ufffdni": "montažni",
    "izri\ufffde": "izriše",
    "za\ufffdene": "zažene",
    "KON\ufffdNO": "KONČNO",
    "RAZ\ufffdLENITEV": "RAZČLENITEV",
    "STRO\ufffdKOV": "STROŠKOV",
    "IZRA\ufffdUNAJ": "IZRAČUNAJ",
    "Monta\ufffda": "Montaža",
    "Ro\ufffdna": "Ročna",
    "razli\ufffdnih": "različnih",
    "Prekli\ufffdi": "Prekliči",
    "Vi\ufffdina": "Višina",
    "g\ufffdltig": "gültig",
    "ko\ufffdarico": "košarico",
    " \ufffde ": " Če ",
    "(\ufffde ": "(Če ",
    ">\ufffde<": ">Če<",
    ">\ufffde ": ">Če ",
    "'\ufffde'": "'Če'"
}

for bad, good in replacements.items():
    text = text.replace(bad, good)

# Also fix the manual edits the user made if they typed "Tilen Petric" instead of "Tilen Petrič"
text = text.replace('value="Tilen Petric"', 'value="Tilen Petrič"')
text = text.replace('>Tilen Petric<', '>Tilen Petrič<')

with open(file_path, "w", encoding="utf-8") as f:
    f.write(text)

print("Fixed")
